site_name: FreiCar Docs
nav:
    - Home: index.md
    - Environment: environment.md
    - FreiCar Overview: nodes/freicar_overview.md
    - FreiCar Map: nodes/freicar_map.md
    - FreiCar Agent: nodes/freicar_agent.md
    - Simulator: simulator.md
    - Competition Rules: competition_rules.md
    - Competition Checklist: competition_checklist.md
    - Presentation Rules: presentation_rules.md
    - Code Testing: code_testing.md    
theme: readthedocs
