site_name: FreiCar Docs
nav:
    - Home: index.md
    - Environment: environment.md
    - FreiCar Overview: nodes/freicar_overview.md
    - FreiCar Map: nodes/freicar_map.md
    - FreiCar Agent: nodes/freicar_agent.md
    - Competition Rules: competition_rules.md
    - Simulator: simulator.md
theme: readthedocs