site_name: FreiCar Docs
nav:
    - Home: index.md
    - Environment: environment.md
    - FreiCar Overview: nodes/freicar_overview.md
    - FreiCar Map: nodes/freicar_map.md
    - FreiCar Agent: nodes/freicar_agent.md
#    - Simulator: simulator.md
    - Mechanical Assembly:
        - 'Index': 'assembly/index.md'
        #- 'Car Preparation': 'assembly/car_prep.md'
        - 'Subassemblies':
            - 'ESC': 'assembly/esc_case.md'
            - 'PC': 'assembly/pc_case.md'
            - 'Front Sensors': 'assembly/front_sensor.md'
            - 'Rear Sensors': 'assembly/rear_sensor.md'
        - 'Car Integration': 'assembly/car_asm.md'

theme: readthedocs